"""Constants for pescoid modelling."""

SNAPSHOT_EVERY_N_STEPS = 10
LEADING_EDGE_THRESHOLD = 0.2
RHO_GATE_CENTER = 0.02
RHO_GATE_WIDTH = 0.01
ETA = 1.0
INITIAL_AMPLITUDE = 1.0
TRANSITION_WIDTH = 1e-2
LENGTH_SCALE = 1.0

OPTIM_PENALTY = 1e4
JITTER = 1e-6
